# Site settings
author: Rocio Escobar
title: Journey to Software Engineering
header-img: img/home-bg.png
email: rocio.x.escobar@gmail.com
copyright_name: Rocio Escobar
description: > # this means to ignore newlines until "baseurl:"
  One step at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rescobar89

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
